version: '3.4'

services:
  api:
    image: ezchat/api
    environment:
      NODE_ENV: production
      APP_PORT: 8000
      SESSION_SECRET: a4hj6a865-*-das56
      DB_HOST: postgres
      REDIS_HOST: redis
    ports:
      - 9000:8000
    build:
      context: .
      dockerfile: ./api/Dockerfile

  web:
    image: ezchat/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:9000
    ports:
      - 80:3000
    build:
      context: .
      dockerfile: ./web/Dockerfile

  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_DB: ezchat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
    - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes 

  pgadmin:
    image: dpage/pgadmin4:4.18
    ports:
      - 8085:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ezchat.io
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
    - pgadmindata:/var/lib/pgadmin
    links:
    - postgres:pgsql-server

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379:0
    ports:
    - 8080:8081

volumes:
  dbdata:
  pgadmindata:
  redisdata: